### ISSUE TITLE
Usage on Windows

### ISSUE THREAD

**Issue by martin5233** [whatacold/ppcompile#5]
First let me thank you for the interesting project. Unfortunately I could not get it to work for my use case. For now I have tried to get it to run on a Windows machine to compile remotely on a Linux machine. What is currently missing is a way to specify the binaries to use: Either you would need customizable variables to set the exact path to 'rsync' and 'expect' or at least you would have to handle the necessary '.exe' extension on Windows. I put 'rsync' and 'expect' into my exec-path, but they were not found, probably because the '.exe' suffix is missing.

**Comment by kenhuang-io** [comment]
Hey Martin, thanks for you participating. I just made a quick fix at this #6 PR, would you like to try it out? As I don't use Windows to test it.
